export const PROJECTS = [
    {
        id: 0,
        title: 'Javascript-Game',
        description: 'A fun game to play',
        img: 'img/...',
        languages: ['Python', 'Javascript', 'HTML'],
        category: 'Game',
        experience: '5 years',
        time: '<5 hours',
        owner_id: 0,
    },
    {
        id: 1,
        title: 'Python-Automation',
        description: 'A fun game to play',
        img: 'img/...',
        languages: ['Python', 'Javascript', 'HTML'],
        category: 'Game' ,
        experience: '1-2 years',
        time: '5-10 hours',
        owner_id: 0,
    },
    {
        id: 2,
        title: 'Python code with SARIMA',
        description: 'I want an expert in python code to use SARIMA package spicily for weather forecasting. With different scenarios from ipcc climate change. I want to build a model to find future weather. please if you do not about that do not waste your time',
        img: 'img/...',
        languages: ['Python', 'Javascript', 'HTML'],
        category: 'Game',
        experience: '10+ years',
        time: '10-20 hours',
        owner_id: 0,
    },
    {
        id: 3,
        title: 'Looking for Python and Google Cloud expert to automate functional ETL python script in Cloud Run',
        description: 'I need assistance with migrating an ETL python script that currently runs locally to a cloud run an instance on GCP. The code is a simple main. py function. Code is currently in a private Github repo. I would like to have CI/CD with this GitHub repo. There may need to be some code updates to support HTTP (required for Cloud Run) and therefore might need to be redesigned into a flask app.',
        img: 'img/...',
        languages: ['Python', 'Javascript', 'HTML'],
        category: 'Game',
        experience: '1-5 years',
        time: '20-40 hours',
        owner_id: 0,
    },
    {
        id: 4,
        title: 'Python web scraper',
        description: 'Creating a web scraper for https://iisda.government.bg/ and scrapping data for government positions and their names, the pages are similar and should be made one scraper and one loop to search in all pages.',
        img: 'img/...',
        languages: ['Python', 'Javascript', 'HTML'],
        category: 'Game',
        experience: '<1 years',
        time: '40+ hours',
        owner_id: 0,
    },
]

